cronJob:
  enabled: false
  useBuildImage: false
  config: []
#     - name: order-update-cron-1
#       image: buildpack-deps:curl
#       schedule: '0 * * * *'
#       successfulJobsHistoryLimit: 3
#       env:
#       - name: test-1
#         value: value-1
#       - name: test-2
#         value: value-2
#       volumeMounts:
#       - name: secrets
#         mountPath: /app/secrets
#         readOnly: true
#       volumes:
#       - name: secrets
#         secret:
#           secretName: secret-name
#     - name: order-update-cron-1
#       image: buildpack-deps:curl
#       schedule: '0 * * * *'
#       successfulJobsHistoryLimit: 3
#       env:
#       - name: test-1
#         value: value-1
#       - name: test-2
#         value: value-2
#       args: ["/bin/sh", "-ec", "curl google.com"]
