{{- if .Values.ingress.enabled -}}
{{- $fullName := include "service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: ingress-{{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .url | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
        {{- end }} 
    {{- end}}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
      {{- range .Values.ingress.paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
      {{- end }}
{{- end }}
