name: Publish Helm Charts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Package Helm Charts
        run: |
          helm package charts/* --destination .
      - name: Generate index.yaml
        run: |
          helm repo index .
          ls
     
      - name: Checkout gh-pages branch
        run: |
          git checkout -b gh-pages
         # git reset --hard
         # git clean -fdx

      - name: Copy charts and index
        run: |
          ls
          cp -n *.tgz .
          cp -n index.yaml .

      - name: Commit and push changes
        run: |
          git add *.tgz index.yaml
          git commit -m "Add charts and index"
          git push -u origin gh-pages
